# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:validate}

# JWT
app.jwt.secret=${APP_JWT_SECRET}

app.verification.endpoint=${APP_VERIFICATION_ENDPOINT}
app.verification.token-minutes=${APP_VERIFICATION_TOKEN_MINUTES:1440}

app.reset-password.endpoint=${APP_RESET_PASSWORD_ENDPOINT}
app.reset-password.token-minutes=${APP_RESET_PASSWORD_TOKEN_MINUTES:30}

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGINS}

# SendGrid
app.mail.from=${APP_MAIL_FROM}
sendgrid.api.key=${SENDGRID_API_KEY}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
app.cloudinary.folder=${APP_CLOUDINARY_FOLDER:cinemax/posters}
app.cloudinary.products-folder=${APP_CLOUDINARY_PRODUCT_FOLDER:cinemax/products}

# Seed admin
app.seed.enabled=${APP_SEED_ENABLED:false}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL:}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:}