# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:validate}

# JWT
app.jwt.secret=${APP_JWT_SECRET}

app.verification.endpoint=${APP_VERIFICATION_ENDPOINT}
app.verification.token-minutes=${APP_VERIFICATION_TOKEN_MINUTES:1440}

app.reset-password.endpoint=${APP_RESET_PASSWORD_ENDPOINT}
app.reset-password.token-minutes=${APP_RESET_PASSWORD_TOKEN_MINUTES:30}

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGINS:https://purple-desert-0b050710.7.azurestaticapps.net}
# SendGrid
app.mail.from=${APP_MAIL_FROM}
sendgrid.api.key=${SENDGRID_API_KEY}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
app.cloudinary.folder=${APP_CLOUDINARY_FOLDER:cinemax/posters}
app.cloudinary.products-folder=${APP_CLOUDINARY_PRODUCT_FOLDER:cinemax/products}

# Seed admin
app.seed.enabled=${APP_SEED_ENABLED:false}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL:}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:}

# Wompi Produccion
app.wompi.environment=${WOMPI_ENVIRONMENT}
app.wompi.public-key=${WOMPI_PUBLIC_KEY}
app.wompi.private-key=${WOMPI_PRIVATE_KEY}
app.wompi.integrity-secret=${WOMPI_INTEGRITY_SECRET}
app.wompi.redirect-url=${WOMPI_REDIRECT_URL}
app.wompi.currency=COP

app.mercadopago.public-key=${MERCADO_PAGO_PUBLIC_KEY}
app.mercadopago.access-token=${MERCADO_PAGO_ACCESS_TOKEN}
app.mercadopago.success-url=https://purple-desert-0b050710.7.azurestaticapps.net/pago/resultado
app.mercadopago.failure-url=https://purple-desert-0b050710.7.azurestaticapps.net/pago/resultado
app.mercadopago.pending-url=https://purple-desert-0b050710.7.azurestaticapps.net/pago/resultado
app.mercadopago.notification-url=
app.mercadopago.currency=COP
app.mercadopago.environment=test