scrape_configs:
  - job_name: 'spring-monitoring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cinemax-backend-env.eba-qvyazdgq.us-east-2.elasticbeanstalk.com:80']